name: Build EXE

on:
  push:
    branches: [ "main" ]  # Запускати при кожному пуші в гілку main

jobs:
  build:
    runs-on: windows-latest  # Використовуємо Windows, щоб отримати .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Вкажіть вашу версію Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py  
        # --onefile збирає все в один .exe
        # --windowed прибирає консоль при запуску (якщо треба)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-python-app
        path: dist/*.exe